### ISSUE TITLE
Demo content?

### ISSUE THREAD

**Issue by Sommerregen** [khanduras/grav-theme-library#1]
Hi @khanduras ,

for my site http://themes.benjamin-regler.de/ I'm trying to showcase all themes available for Grav and I really like to add yours, too. Unfortunately there is no demo content available, but I've seen there is a live site (http://chiefqualakon.net/). Is it possible to get this demo content (the page files and the config)?

**Comment by khanduras** [comment]
Hello, 

I saw your project and am quite impressed by it. Will themes and plugins update periodically? 

I'll create some demo content and upload it to the github repo. 

Cheers

Edit: This is done, has to push through GPM first

**Comment by Sommerregen** [comment]
Hi @khanduras,

cool! My project runs from a single Grav install and uses the themes and plugins versions available via GPM. Here each theme has a different `pages` and `config` folder. The rest will be shared by all installations. In order to update them I only have to run the command `bin/gpm update`. However the only thing I have to do manually is when changes in the demo content or config changes happen. Then I have to copy them manually to their respective folders (but this is a simple task and should happens rarely).

I will upload your demo content today. The demo to your theme will be available at http://themes.benjamin-regler.de/library/ .

Thanks :smile: 

**UPDATE:** Got it to work. FYI because not mentioned in docs this theme needs https://github.com/khanduras/grav-plugin-uikitifier in order to run. Better include this informationation in the README, the file in the composer.json and an `dependencies` entry in the blueprints.yaml .
