### ISSUE TITLE
CSS not being applied

### ISSUE THREAD

**Issue by washere** [khanduras/grav-theme-library#4]
It is not applying the CSS style.

**Comment by washere** [comment]
I have installed many Grav themes, none gave me this problem.
Problem persists in other sections too

**Comment by khanduras** [comment]
Hi @washere 

I'll take a look and let you know what's going on. If you hit F12 to inspect the page, are there any errors there?

**Comment by khanduras** [comment]
Hi there, 

Looks like I loaded UIKit using a separate plugin: https://github.com/khanduras/grav-plugin-uikitifier

You should be able to load it from the GPM by searching UIKitifier. Let me know how that works out for you.

Cheers,

Daniel

**Comment by khanduras** [comment]
Also, if your website is going to be publicly facing, let me know the URL and I can use yours as an example site.

**Comment by washere** [comment]
Closing this as installing the prerequisite UIKitifier fixed it.
